---
## /* vim: set tabstop=2 softtabstop=2 shiftwidth=2 expandtab smarttab autoindent: */

- name: 'Make sure the locales package is available'
  ansible.builtin.package:
    name: '{{ locales_package_name }}'
    state: '{{ locales_package_state }}'

- name: 'Check /etc/locale.gen'
  ansible.builtin.stat:
    path: '/etc/locale.gen'
  register: 'localegen'

- name: 'Make sure /etc/locale.gen exists'
  ansible.builtin.file:
    path: '/etc/locale.gen'
    state: 'touch'
    owner: 'root'
    group: 'root'
    mode: 'u=rw,go=r'
  when: 'not localegen.stat.exists'

- name: 'Generate the locales'
  community.general.locale_gen:
    name: '{{ item }}'
    state: 'present'
  loop: '{{ locales | flatten(levels=1) }}'
